# ============================================================
# Archivo de configuración de syncgitconfig
# ============================================================
# Edita con cuidado y reinicia servicios tras cambios:
#   sudo systemctl restart syncgitconfig-watch.service
#   sudo systemctl restart syncgitconfig.service
# ============================================================

# ---- Parámetros globales ----
env: __ENV__               # Entorno (prod, pre, dev, test)
host: __HOST__             # Hostname (o "auto" para autodetectar)
repo_path: __REPO_PATH__   # Ruta local donde se clona el repo
remote_url: __REMOTE_URL__ # URL remota del repo (HTTPS/SSH)
cooldown: __COOLDOWN__     # Intervalo en segundos entre syncs

# ---- Modelo declarativo por entorno/host ----
environments:
  __ENV__:
    hosts:
      __HOST__:
        apps:
          systemd:
            paths:
              - /etc/systemd/system
          # phpipam:
          #   paths:
          #     - /var/www/phpipam

# ---- Watchers personalizados (opcional) ----
# watch_paths:
#   - /etc/systemd

# ---- Snapshot directo (legacy) ----
# paths:
#   - /etc/systemd/system
#   - /var/www/phpipam

# ---- Exclusiones (opcional) ----
# exclude:
#   - "*.log"
#   - "/etc/nginx/sites-enabled/default"

# ---- Autenticación ----
auth:
  method: https_token        # https_token | https_netrc | ssh
  username: syncgit-bot
  token_file: /etc/syncgitconfig/credentials/.git-credentials
  # token_inline: "PON TEMPORALMENTE EL TOKEN AQUÍ Y SE MIGRA"
  # netrc_file: /root/.netrc
  # ssh_key_path: /root/.ssh/id_ed25519
  # ssh_known_hosts: /etc/ssh/ssh_known_hosts
  # ssh_extra_args: "-o IdentitiesOnly=yes"

# ---- Apps manuales (formato clásico) ----
# apps:
#   - name: systemd
#     dest: "apps/systemd"
#     sources:
#       - path: "/etc/systemd/system"
#         type: dir
