# === Núcleo ===
repo_path: /opt/configs-host                  # checkout local del repo de ESTE servidor
remote_url: https://gitea.example.local/ORG/configs-host.git
env: prod
host: auto                                    # o un FQDN fijo como "host01.example.local"
staging_path: /var/lib/syncgitconfig/staging
cooldown_seconds: 60

environments:
  prod:
    hosts:
      auto:
        apps:
          systemd:
            paths:
              - /etc/systemd/system
          # phpipam:
          #   paths:
          #     - /var/www/phpipam
# watch_paths:
#   - "/etc/systemd/system"

# === Autenticación (HTTPS + token) ===
auth:
  method: https_token
  username: syncgit-bot
  token_file: /etc/syncgitconfig/credentials/.git-credentials
  # token_inline: "PON_AQUI_TU_TOKEN_Y_LUEGO_SE_BORRA"
  # method: https_netrc
  # netrc_file: /root/.netrc
  # method: ssh
  # ssh_key_path: /root/.ssh/id_ed25519
  # ssh_known_hosts: /etc/ssh/ssh_known_hosts
  # ssh_extra_args: "-o IdentitiesOnly=yes"

# === Exclusiones globales ===
exclude:
  - "*.key"
  - "*.pem"
  - "id_*"
  - "secrets/**"
  - "*.p12"
  - "*.jks"
  - "*.srl"

# === Modelo por aplicación ===
# apps:
#   - name: systemd
#     dest: "apps/systemd"
#     sources:
#       - path: "/etc/systemd/system"
#         type: dir
#         strip_prefix: "/etc/systemd/system"

  # Ejemplos para activar cuando quieras:
  # - name: ssh
  #   dest: "apps/ssh"
  #   sources:
  #     - path: "/etc/ssh/sshd_config"
  #       type: file
  #       strip_prefix: "/etc/ssh"

  # - name: monitoring
  #   dest: "apps/monitoring"
  #   sources:
  #     - path: "/etc/nagios"
  #       type: dir
  #       strip_prefix: "/etc/nagios"
